language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

services:
  - postgresql

install:
  - ls -al 

script:
  - go get -u -v github.com/gobuffalo/buffalo/buffalo
  - ls -al $GOPATH/bin
  - buffalo version
  - buffalo pop create -a
  - go test ./...
  - echo "testing buffalo build"
  - npm install
  - buffalo build

notifications:
  email:
    on_success: change
    on_failure: always
