language: go

go:
  - 1.9.x
  - "1.10"

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

services:
  - postgresql

install:
  - ls -al 
  - dep ensure

script:
  - go get -u -v github.com/gobuffalo/buffalo/buffalo
  - ls -al $GOPATH/bin
  - buffalo db create -a
  - go test ./...
  - echo "testing buffalo build"
  - npm install
  - buffalo build

notifications:
  email:
    on_success: change
    on_failure: always
